apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
#cmNsYXJlbmNlMTIzQGdtYWlsLmNvbQ==
  PG_USER_EMAIL: cmNsYXJlbmNlMTIzQGdtYWlsLmNvbQ==
  PG_PASSWORD: dmxhZG15bGVzc2VydmljZW5mcGc=